// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDje4TYPs2XPUz6RAnkQMkafCycudv69vM',
    appId: '1:127869269941:android:67d8fb0ae0545978ca4bfc',
    messagingSenderId: '127869269941',
    projectId: 'newson-dea6b',
    databaseURL: 'https://newson-dea6b-default-rtdb.firebaseio.com',
    storageBucket: 'newson-dea6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZQFDLcfyOXQqEt9M5mDSQkwMOBl643II',
    appId: '1:127869269941:ios:b4f754ab7decdd6cca4bfc',
    messagingSenderId: '127869269941',
    projectId: 'newson-dea6b',
    databaseURL: 'https://newson-dea6b-default-rtdb.firebaseio.com',
    storageBucket: 'newson-dea6b.firebasestorage.app',
    androidClientId: '127869269941-sjls3shqo436vt3oq9kqc4rlqimsb3rh.apps.googleusercontent.com',
    iosClientId: '127869269941-pquese7dne3sl1fhaolvlap5rs86c3vm.apps.googleusercontent.com',
    iosBundleId: 'com.app.newson',
  );
}
